
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template
Driver_name=com.microsoft.sqlserver.jdbc.SQLServerDriver
URL=jdbc:sqlserver://localhost:1433;database=Arogya_Ram_latest_NEW
Uname=ta
password=12345